import "../styles/globals.css";
import { Inter } from "next/font/google";
import Navbar from '../components/Navbar'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='h-full w-full border-b-2 border-gray-500 z-10 sticky top-0'>
            <Navbar/>
        </div>
        {children}
        <script
          src="https://kit.fontawesome.com/f8f9825bbd.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
